"""
trade.py

Represents a single executed trade (fill).

A Trade is immutable and records the actual execution generated by
the broker.

One order may produce multiple trades.
"""

from __future__ import annotations

from dataclasses import dataclass, field
from datetime import datetime, timezone
from decimal import Decimal

from broker.enums import OrderSide


@dataclass(frozen=True, slots=True)
class Trade:
    """
    Represents one executed trade.

    A Trade is created by the broker whenever an order (or part of an
    order) executes.
    """

    trade_id: str
    order_id: str

    symbol: str

    side: OrderSide

    quantity: int

    price: Decimal

    commission: Decimal = Decimal("0")

    timestamp: datetime = field(
        default_factory=lambda: datetime.now(timezone.utc)
    )

    def __post_init__(self) -> None:

        object.__setattr__(
            self,
            "symbol",
            self.symbol.upper().strip(),
        )

        if not self.symbol:
            raise ValueError("Symbol cannot be empty.")

        if self.quantity <= 0:
            raise ValueError(
                "Quantity must be greater than zero."
            )

        price = Decimal(self.price)

        if price <= 0:
            raise ValueError(
                "Execution price must be greater than zero."
            )

        commission = Decimal(self.commission)

        if commission < 0:
            raise ValueError(
                "Commission cannot be negative."
            )

        object.__setattr__(self, "price", price)
        object.__setattr__(self, "commission", commission)

    # ---------------------------------------------------------
    # Convenience Properties
    # ---------------------------------------------------------

    @property
    def gross_value(self) -> Decimal:
        """
        Quantity × execution price.
        """

        return self.price * self.quantity

    @property
    def net_value(self) -> Decimal:
        """
        Cash movement including commission.

        BUY:
            Gross + Commission

        SELL:
            Gross - Commission
        """

        if self.is_buy:
            return self.gross_value + self.commission

        return self.gross_value - self.commission

    @property
    def is_buy(self) -> bool:
        return self.side == OrderSide.BUY

    @property
    def is_sell(self) -> bool:
        return self.side == OrderSide.SELL

    # ---------------------------------------------------------

    def __repr__(self) -> str:

        return (
            "Trade("
            f"id={self.trade_id}, "
            f"order={self.order_id}, "
            f"symbol={self.symbol}, "
            f"side={self.side.name}, "
            f"qty={self.quantity}, "
            f"price={self.price}, "
            f"commission={self.commission})"
        )